### ISSUE TITLE
Just a general Question about OpaqueMail vs MailKit

### ISSUE THREAD

**Issue by zaryk** [bertjohnson/OpaqueMail#42]
I have seen MailKit mentioned in at least one other issue, so I was wondering more about the differences between MailKit and OpaqueMail, and what is the purpose or goal of OpaqueMail.  More or less, why should anyone use OpaqueMail over MailKit.  Looking at the initial code page, it seems Mailkit has more features, but it may just be a high level explanation over a more detailed explanation.

**Comment by bertjohnson** [comment]
OpaqueMail was created before MailKit to simplify IMAP, POP3, and SMTP while dealing with email encryption. When OpaqueMail was created in 2013, I think it was the best and most compatible library for handling S/MIME for all protocols.  It was purposely designed to mimic the "System.Net.Mail" patterns to make it easy to convert to.

The author of MailKit seems to frequent this project and has linked to his project on a few occasions.  I have not used MailKit, but it seems like a great library. The author is very focused on performance, so I'm guessing it's faster and he maintains it actively, so it may support more of the email RFCs at this point.

OpaqueMail is very stable.  I don't have any enhancements planned for the near future.  Since MailKit is more actively maintained, that may be a better choice for you.  I recommend trying a few libraries and using whatever has the features and syntax that you prefer.

**Comment by zaryk** [comment]
Thanks for the quick response.

**Comment by jstedfast** [comment]
I think Bert's answer pretty much sums it up, but if you have any question about MimeKit or MailKit that you'd like to ask me, just shoot me an email or something (e.g. post a question in the MimeKit/MailKit issue tracker) and I'd be happy to answer any questions you have.

The only thing I'd add to Bert's statement is that MimeKit and MailKit are designed with the intention of making it possible to write a fully featured email client and so provide a lot of functionality for that purpose.

It's also very *very* fast :-)
