### ISSUE TITLE
GetMessageHelper() seekStart and seekEnd won't work

### ISSUE THREAD

**Issue by jstedfast** [bertjohnson/OpaqueMail#48]
While trying to help someone fix another issue reported in GetMessageHelper(), I noticed that it takes a seekStart and seekEnd.

These parameters allow fetching a substream of the message but GetMessageHelper returns a MailMessage and later in the code, it attempts to parse the substream as a MailMessage.

This won't be doable if I attempt to fetch a substream range that does not include the headers.

**Comment by bertjohnson** [comment]
Thanks Jeff, good catch. The "seekStart" and "seekEnd" should be useful, but haven't worked since rearchitecting version 2.0.

If I find the time, I may rework it so partial strings / bytestreams can be returned instead of complete MailMessage objects. For now, I've removed those parameters from OpaqueMail 2.3.0.

Thanks for all of your involvement.

**Comment by bertjohnson** [comment]
2.3.4 added GetMessagePartial() to retrieve arbitrary substrings based on seekStart and seekEnd parameters.
