### ISSUE TITLE
Deleting PoP3 mails by UID

### ISSUE THREAD

**Issue by Kermel** [bertjohnson/OpaqueMail#57]
Using pop3client.DeleteMessage(string) (where string means the UID) doesn't work. I checked the internal implementation and it is rather suspicious that it works _exactly_ like DeleteMessage(int) (where int means the message index).

As per POP3 protocol specification, DELE command accepts the message number (the index) as a parameter so calling the same command with UID can hardly do the same.
(and my few test confirm my doubts... - messages are not deleted)

**Comment by bertjohnson** [comment]
Thanks for the report, Kermel. You're right, POP3 servers don't support deletion based on UID. That shouldn't have survived so long since it never worked.

The UID variants of DeleteMessage and DeleteMessages are removed as of release 2.4.4.

For anyone stumbling on this, POP3 deletion needs to be done based on the message index. IMAP supports deletion based on UID.
